# Generated by Django 5.1.7 on 2025-04-02 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_terms_accepted_at'),
    ]

    operations = [
    ]
